name: "Code Checks"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  packages: read

jobs:
  check-code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      # Lint and Format everything
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/super-linter-configurations
          YAML_ERROR_ON_WARNING: true
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_CSS: false
          VALIDATE_JSON: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          VALIDATE_TSX_PRETTIER: false

  check-markdown-links:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check Markdown links
        uses: UmbrellaDocs/action-linkspector@v1.2.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/other-configurations/.linkspector.yml
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter

  check-justfile-format:
    name: Check Justfile Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@v2
      - name: Check Justfile Format
        run: just format-check

  run-zizmor:
    name: Check GitHub Actions with zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Scanner Dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Run zizmor 🌈
        run: uv --project scanner run zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3.28.11
        with:
          sarif_file: results.sarif
          category: zizmor

  lefthook-validate:
    name: Lefthook Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5.3.1
        with:
          version: "latest"
      - name: Run Lefthook Validate
        run: uvx lefthook validate

  run-codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    strategy:
      matrix:
        language: [python, actions]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.28.11
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality
          config-file: .github/other-configurations/codeql-config.yml
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.28.11

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Scanner Dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Run Unit Tests
        run: just scanner::unit-test
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-scanner-python-code-checks:
    name: Run Scanner Python Code Checks
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Scanner Dependencies
        uses: ./.github/actions/setup-scanner-dependencies
      - name: Generate Ruff Sarif
        run: just scanner::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.28.11
        with:
          sarif_file: scanner/ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Format (Ruff)
        run: just scanner::ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"
      - name: Check Python Code Linting (Ruff)
        run: just scanner::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"
      - name: Check Python Code for Dead Code (Vulture)
        run: just scanner::vulture

  run-diagrams-python-code-checks:
    name: Run Diagrams Python Code Checks
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Diagrams Dependencies
        uses: ./.github/actions/setup-diagrams-dependencies
      - name: Generate Ruff Sarif
        run: just diagrams::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "sarif"
          RUFF_OUTPUT_FILE: "ruff-results.sarif"
        continue-on-error: true
      - name: Upload Ruff analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3.28.11
        with:
          sarif_file: diagrams/ruff-results.sarif
          wait-for-processing: true
      - name: Check Python Code Format (Ruff)
        run: just diagrams::ruff-format-check
        env:
          RUFF_OUTPUT_FORMAT: "github"
      - name: Check Python Code Linting (Ruff)
        run: just diagrams::ruff-lint-check
        env:
          RUFF_OUTPUT_FORMAT: "github"

  run-code-limit:
    name: Run CodeLimit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Run Code Limit"
        uses: getcodelimit/codelimit-action@v1
